# http://jevon.org/wiki/Google_OAuth2_with_Ruby_on_Rails

OAUTH_CLIENT_ID: 1089493795741-kcc1gbk7pt6sqfpsv6fdaiv57vpe1ksb.apps.googleusercontent.com
OAUTH_CLIENT_SECRET: nzAmJL-k1t-RIXhxIo5vUBei 
APPLICATION_CONFIG_SECRET_TOKEN: 1089493795741-kcc1gbk7pt6sqfpsv6fdaiv57vpe1ksb.apps.googleusercontent.com-a-long-secret
